import { SxProps } from "@mui/material";

export const StyleSheet = {
  Main: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    height: "100vh",
  },

  headerContent: {
    color: "#afb8c2",
    display: "flex",
    justifyContent: "flex-start",
    alignContent: "center",
    fontSize: "25px",
    paddingLeft: "55px",
    pt: "5px",
  },
  upload: { display: "none" },

  memeContainer: {
    width: "max-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: { xs: "column", sm: "column", lg: "row" },
    background: "#333333",
    my: "50px",
  },
  imageContainer: {
    border: "2px solid grey",
    position: "relative",
    width: { xs: "475px", md: "99%", lg: "600px", xl: "580px" },
    height: {
      xs: "100%",
      md: "100%",
      lg: "500px",
      xl: "500px",
    },
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    alignSelf: "flex-start",
    mt: 5,
    ml: 2,
    mb: 2,
  },

  imgContent: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: { xs: "250px", sm: "300px", lg: "400px", xl: "500px" },
  },
  imgContent_TopTextBox: {
    width: "fit-content",
    fontWeight: "500",
    color: "black",
    position: "absolute",
    left: { xs: "25%", sm: "40%", lg: "30%", xl: "40%" },
    top: "5%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    inlineSize: "200px",
    alignSelf: "flex-end",
    cursor: "move",
    p: 1,
    minWidth: "200px",
    minHeight: "5vh",
  },

  images: {
    display: { xs: "flex", lg: "flex" },
    overflowX: "scroll",
    visibility: "scroll",
    width: "450px",
    height: "100px",
    border: "1px solid",
  },
  echImage: { width: "100%", height: "100%", mr: "5px" },
  InputFields: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
    margin: "10px",
  },
  uploadBtn: {
    border: "1px solid grey",
    width: "50%",
    fontSize: "16px",
    mb: 2,
    p: 1,
    color: "#ccc",
    cursor: "pointer",
    "&:hover": {
      border: "1px solid #555",
    },
  },
  Input: {
    border: "2px solid grey",
    margin: "20px",
    padding: "10px 50px",
    fontSize: "20px",
    background: "#222222",
    color: "white",
    width: "12em",
  },
  inputContainer: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
  },
  inputContainer_innerBox: {
    height: "4em",
  },
  inputColorField: {
    width: "30px",
    height: "30px",
    outline: "none",
    border: "none",
    borderColor: "grey",
    borderRadius: "5px",
    mr: 1,
    "&::-webkit-color-swatch-wrapper": { p: 0 },
  },
  uploadFiles: { mt: "50px", mb: "20px" },
  btnsContainer: {
    mt: 2,
    width: "100%",
  },
  addText: {
    float: "right",
    height: "30px",
    textTransform: "capitalize",
    fontSize: "12px",
    border: "1px solid #ccc",
    color: "white",
    mr: 2,
    mb: 2,
    "&:hover": {
      color: "white",
      border: "1px solid grey",
    },
  },
} satisfies Record<string, SxProps>;
